The 'BaseGeometry' test module
==============================

Using 'BaseGeometry'
--------------------

>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
>>> bg = BaseGeometry()

>>> bg.integer_validator("age", 20)

>>> bg.integer_validator("age", (20, 62))
Traceback (most recent call last):
TypeError: age must be an integer

>>> bg.integer_validator("age", [20, 62])
Traceback (most recent call last):
TypeError: age must be an integer

>>> bg.integer_validator("age", {20, 62})
Traceback (most recent call last):
TypeError: age must be an integer

>>> bg.integer_validator("age", [20])
Traceback (most recent call last):
TypeError: age must be an integer

>>> bg.integer_validator("age", True)
Traceback (most recent call last):
TypeError: age must be an integer

>>> bg.integer_validator("name", "John")
Traceback (most recent call last):
TypeError: name must be an integer

>>> bg.integer_validator("age", 0)
Traceback (most recent call last):
ValueError: age must be greater than 0

>>> bg.integer_validator("distance", -4)
Traceback (most recent call last):
ValueError: distance must be greater than 0

>>> bg.integer_validator("age", 5.6)
Traceback (most recent call last):
TypeError: age must be an integer

>>> bg.integer_validator("age", )
Traceback (most recent call last):
TypeError: integer_validator() missing 1 required positional argument: 'value'

>>> bg.integer_validator(, 5.6)
Traceback (most recent call last):
SyntaxError: invalid syntax

>>> bg.integer_validator()
Traceback (most recent call last):
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

>>> bg.integer_validator("age", None)
Traceback (most recent call last):
TypeError: age must be an integer

>>> bg.integer_validator(None, 56)

>>> bg.integer_validator("HSBC", 56, 89)
Traceback (most recent call last):
TypeError: integer_validator() takes 3 positional arguments but 4 were given

>>> bg.integer_validator(75, "John")
Traceback (most recent call last):
TypeError: 75 must be an integer

>>> bg.area()
Traceback (most recent call last):
Exception: area() is not implemented